export * from "./utils/core.js";
export type TFunction = import("./utils/TFunction.js").TFunction;
export default NaN0;
export type ModelOptions = import("./Model").ModelOptions;
import { FilterString } from './domain/index.js';
import { FullObject } from './domain/index.js';
import { UndefinedObject } from './domain/index.js';
import { ObjectWithAlias } from './domain/index.js';
import { ContainerObject } from './domain/index.js';
import { NonEmptyObject } from './domain/index.js';
import clone from './utils/clone.js';
import merge from './utils/merge.js';
import { Parser } from './domain/index.js';
import { Node } from './domain/index.js';
import { NaN0 } from './domain/index.js';
import resolveAliases from './utils/resolveAliases.js';
import resolveDefaults from './utils/resolveDefaults.js';
import resolveValidation from './utils/resolveValidation.js';
import { Model } from './Model.js';
import { ModelError } from './domain/index.js';
import { createT } from './utils/TFunction.js';
export { FilterString, FullObject, UndefinedObject, ObjectWithAlias, ContainerObject, NonEmptyObject, clone, merge, Parser, Node, NaN0, resolveAliases, resolveDefaults, resolveValidation, Model, ModelError, createT, createT as TFunction };
